application_name:
  type: "string"
  value: "meal-api"
env:
  type: "string"
  value: "LOCAL"
the_meals_db_http_url:
  type: "string"
  value: "https://www.themealdb.com/api/json/v1/1/random.php"
the_meals_db_http_timeout:
  type: "duration"
  value: "5s"
