// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: meal/v1/meal.proto

package meal_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SearchMealsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SearchMealsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchMealsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchMealsRequestMultiError, or nil if none found.
func (m *SearchMealsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchMealsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetQuery()) > 100 {
		err := SearchMealsRequestValidationError{
			field:  "Query",
			reason: "value length must be at most 100 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetIncludeIngredientIds()) > 10 {
		err := SearchMealsRequestValidationError{
			field:  "IncludeIngredientIds",
			reason: "value must contain no more than 10 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetIncludeIngredientIds() {
		_, _ = idx, item

		if item < 1 {
			err := SearchMealsRequestValidationError{
				field:  fmt.Sprintf("IncludeIngredientIds[%v]", idx),
				reason: "value must be greater than or equal to 1",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(m.GetExcludeIngredientIds()) > 10 {
		err := SearchMealsRequestValidationError{
			field:  "ExcludeIngredientIds",
			reason: "value must contain no more than 10 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetExcludeIngredientIds() {
		_, _ = idx, item

		if item < 1 {
			err := SearchMealsRequestValidationError{
				field:  fmt.Sprintf("ExcludeIngredientIds[%v]", idx),
				reason: "value must be greater than or equal to 1",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if val := m.GetPageSize(); val < 1 || val > 100 {
		err := SearchMealsRequestValidationError{
			field:  "PageSize",
			reason: "value must be inside range [1, 100]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPage() < 1 {
		err := SearchMealsRequestValidationError{
			field:  "Page",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.CategoryId != nil {

		if m.GetCategoryId() < 1 {
			err := SearchMealsRequestValidationError{
				field:  "CategoryId",
				reason: "value must be greater than or equal to 1",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.CuisineId != nil {

		if m.GetCuisineId() < 1 {
			err := SearchMealsRequestValidationError{
				field:  "CuisineId",
				reason: "value must be greater than or equal to 1",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.MaxCookingTimeMinutes != nil {

		if val := m.GetMaxCookingTimeMinutes(); val < 1 || val > 600 {
			err := SearchMealsRequestValidationError{
				field:  "MaxCookingTimeMinutes",
				reason: "value must be inside range [1, 600]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return SearchMealsRequestMultiError(errors)
	}

	return nil
}

// SearchMealsRequestMultiError is an error wrapping multiple validation errors
// returned by SearchMealsRequest.ValidateAll() if the designated constraints
// aren't met.
type SearchMealsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchMealsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchMealsRequestMultiError) AllErrors() []error { return m }

// SearchMealsRequestValidationError is the validation error returned by
// SearchMealsRequest.Validate if the designated constraints aren't met.
type SearchMealsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchMealsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchMealsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchMealsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchMealsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchMealsRequestValidationError) ErrorName() string {
	return "SearchMealsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SearchMealsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchMealsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchMealsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchMealsRequestValidationError{}

// Validate checks the field values on SearchMealsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SearchMealsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchMealsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchMealsResponseMultiError, or nil if none found.
func (m *SearchMealsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchMealsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetMeals() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SearchMealsResponseValidationError{
						field:  fmt.Sprintf("Meals[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SearchMealsResponseValidationError{
						field:  fmt.Sprintf("Meals[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SearchMealsResponseValidationError{
					field:  fmt.Sprintf("Meals[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TotalCount

	// no validation rules for Page

	// no validation rules for PageSize

	// no validation rules for HasNextPage

	if len(errors) > 0 {
		return SearchMealsResponseMultiError(errors)
	}

	return nil
}

// SearchMealsResponseMultiError is an error wrapping multiple validation
// errors returned by SearchMealsResponse.ValidateAll() if the designated
// constraints aren't met.
type SearchMealsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchMealsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchMealsResponseMultiError) AllErrors() []error { return m }

// SearchMealsResponseValidationError is the validation error returned by
// SearchMealsResponse.Validate if the designated constraints aren't met.
type SearchMealsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchMealsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchMealsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchMealsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchMealsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchMealsResponseValidationError) ErrorName() string {
	return "SearchMealsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SearchMealsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchMealsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchMealsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchMealsResponseValidationError{}

// Validate checks the field values on Meal with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Meal) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Meal with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in MealMultiError, or nil if none found.
func (m *Meal) ValidateAll() error {
	return m.validate(true)
}

func (m *Meal) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ExternalId

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for ImageUrl

	if all {
		switch v := interface{}(m.GetCategory()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MealValidationError{
					field:  "Category",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MealValidationError{
					field:  "Category",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCategory()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MealValidationError{
				field:  "Category",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCuisine()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MealValidationError{
					field:  "Cuisine",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MealValidationError{
					field:  "Cuisine",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCuisine()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MealValidationError{
				field:  "Cuisine",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetIngredients() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, MealValidationError{
						field:  fmt.Sprintf("Ingredients[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, MealValidationError{
						field:  fmt.Sprintf("Ingredients[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MealValidationError{
					field:  fmt.Sprintf("Ingredients[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for CookingTimeMinutes

	if m.VideoUrl != nil {
		// no validation rules for VideoUrl
	}

	if len(errors) > 0 {
		return MealMultiError(errors)
	}

	return nil
}

// MealMultiError is an error wrapping multiple validation errors returned by
// Meal.ValidateAll() if the designated constraints aren't met.
type MealMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MealMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MealMultiError) AllErrors() []error { return m }

// MealValidationError is the validation error returned by Meal.Validate if the
// designated constraints aren't met.
type MealValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MealValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MealValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MealValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MealValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MealValidationError) ErrorName() string { return "MealValidationError" }

// Error satisfies the builtin error interface
func (e MealValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMeal.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MealValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MealValidationError{}

// Validate checks the field values on Category with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Category) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Category with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CategoryMultiError, or nil
// if none found.
func (m *Category) ValidateAll() error {
	return m.validate(true)
}

func (m *Category) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if m.Description != nil {
		// no validation rules for Description
	}

	if len(errors) > 0 {
		return CategoryMultiError(errors)
	}

	return nil
}

// CategoryMultiError is an error wrapping multiple validation errors returned
// by Category.ValidateAll() if the designated constraints aren't met.
type CategoryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CategoryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CategoryMultiError) AllErrors() []error { return m }

// CategoryValidationError is the validation error returned by
// Category.Validate if the designated constraints aren't met.
type CategoryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CategoryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CategoryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CategoryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CategoryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CategoryValidationError) ErrorName() string { return "CategoryValidationError" }

// Error satisfies the builtin error interface
func (e CategoryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCategory.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CategoryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CategoryValidationError{}

// Validate checks the field values on Cuisine with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Cuisine) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Cuisine with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in CuisineMultiError, or nil if none found.
func (m *Cuisine) ValidateAll() error {
	return m.validate(true)
}

func (m *Cuisine) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if m.Description != nil {
		// no validation rules for Description
	}

	if len(errors) > 0 {
		return CuisineMultiError(errors)
	}

	return nil
}

// CuisineMultiError is an error wrapping multiple validation errors returned
// by Cuisine.ValidateAll() if the designated constraints aren't met.
type CuisineMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CuisineMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CuisineMultiError) AllErrors() []error { return m }

// CuisineValidationError is the validation error returned by Cuisine.Validate
// if the designated constraints aren't met.
type CuisineValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CuisineValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CuisineValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CuisineValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CuisineValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CuisineValidationError) ErrorName() string { return "CuisineValidationError" }

// Error satisfies the builtin error interface
func (e CuisineValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCuisine.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CuisineValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CuisineValidationError{}

// Validate checks the field values on MealIngredient with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MealIngredient) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MealIngredient with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MealIngredientMultiError,
// or nil if none found.
func (m *MealIngredient) ValidateAll() error {
	return m.validate(true)
}

func (m *MealIngredient) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IngredientId

	// no validation rules for IngredientName

	// no validation rules for Measure

	// no validation rules for Position

	if len(errors) > 0 {
		return MealIngredientMultiError(errors)
	}

	return nil
}

// MealIngredientMultiError is an error wrapping multiple validation errors
// returned by MealIngredient.ValidateAll() if the designated constraints
// aren't met.
type MealIngredientMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MealIngredientMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MealIngredientMultiError) AllErrors() []error { return m }

// MealIngredientValidationError is the validation error returned by
// MealIngredient.Validate if the designated constraints aren't met.
type MealIngredientValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MealIngredientValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MealIngredientValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MealIngredientValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MealIngredientValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MealIngredientValidationError) ErrorName() string { return "MealIngredientValidationError" }

// Error satisfies the builtin error interface
func (e MealIngredientValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMealIngredient.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MealIngredientValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MealIngredientValidationError{}
