// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTheMealsDbClientConfig creates a new instance of MockTheMealsDbClientConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTheMealsDbClientConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTheMealsDbClientConfig {
	mock := &MockTheMealsDbClientConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTheMealsDbClientConfig is an autogenerated mock type for the TheMealsDbClientConfig type
type MockTheMealsDbClientConfig struct {
	mock.Mock
}

type MockTheMealsDbClientConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTheMealsDbClientConfig) EXPECT() *MockTheMealsDbClientConfig_Expecter {
	return &MockTheMealsDbClientConfig_Expecter{mock: &_m.Mock}
}

// Timeout provides a mock function for the type MockTheMealsDbClientConfig
func (_mock *MockTheMealsDbClientConfig) Timeout() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Timeout")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockTheMealsDbClientConfig_Timeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Timeout'
type MockTheMealsDbClientConfig_Timeout_Call struct {
	*mock.Call
}

// Timeout is a helper method to define mock.On call
func (_e *MockTheMealsDbClientConfig_Expecter) Timeout() *MockTheMealsDbClientConfig_Timeout_Call {
	return &MockTheMealsDbClientConfig_Timeout_Call{Call: _e.mock.On("Timeout")}
}

func (_c *MockTheMealsDbClientConfig_Timeout_Call) Run(run func()) *MockTheMealsDbClientConfig_Timeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTheMealsDbClientConfig_Timeout_Call) Return(duration time.Duration) *MockTheMealsDbClientConfig_Timeout_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockTheMealsDbClientConfig_Timeout_Call) RunAndReturn(run func() time.Duration) *MockTheMealsDbClientConfig_Timeout_Call {
	_c.Call.Return(run)
	return _c
}

// Url provides a mock function for the type MockTheMealsDbClientConfig
func (_mock *MockTheMealsDbClientConfig) Url() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Url")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTheMealsDbClientConfig_Url_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Url'
type MockTheMealsDbClientConfig_Url_Call struct {
	*mock.Call
}

// Url is a helper method to define mock.On call
func (_e *MockTheMealsDbClientConfig_Expecter) Url() *MockTheMealsDbClientConfig_Url_Call {
	return &MockTheMealsDbClientConfig_Url_Call{Call: _e.mock.On("Url")}
}

func (_c *MockTheMealsDbClientConfig_Url_Call) Run(run func()) *MockTheMealsDbClientConfig_Url_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTheMealsDbClientConfig_Url_Call) Return(s string) *MockTheMealsDbClientConfig_Url_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTheMealsDbClientConfig_Url_Call) RunAndReturn(run func() string) *MockTheMealsDbClientConfig_Url_Call {
	_c.Call.Return(run)
	return _c
}
